### ISSUE TITLE
channel level plugin

### ISSUE THREAD

**Issue by yields** [slate/slate#49]
for example #components a user types `size component/dom` a plugin might show `6kb, ~120sloc`.

**Comment by tj** [comment]
most of that could be done a the bot-level, but for things that bots aren't great for like auto-completing lists of github issues etc I'd like to have in plugins :D

**Comment by tj** [comment]
or stuff like your company's irc could have a block on top with some realtime stats and stuff like that

**Comment by yields** [comment]
> or stuff like your company's irc could have a block on top with some realtime stats and stuff like that

sounds cool!

there's so many plugin ideas in my head right now haha :p
