### ISSUE TITLE
Command + keybindings do not function in Windows

### ISSUE THREAD

**Issue by weswigham** [slate/slate#71]
Being unable to use any of them makes it a bit awkward to try to use.

**Comment by rnarian** [comment]
Neither do they on OS X...

**Comment by rnarian** [comment]
Seems like they are not even implemented yet?

build/build.js:5530:

```
shortcuts.bind('command + r', 'refresh the page', function(){ location.reload() });
shortcuts.bind('command + C', 'show connections', function(){});
shortcuts.bind('command + c', 'show channels', function(){});
shortcuts.bind('command + u', 'show users', function(){});
shortcuts.bind('command + k', 'clear chat log', function(){});
```

**Comment by tj** [comment]
yea that's why the readme says "it's not quite in a usable state", still need to finish some dialogs etc

**Comment by MCB-PRO-27** [comment]
I gave u all gold- use ur intellect to see not read code!!! Look again!!!!

**Comment by juliangruber** [comment]
i think it should be `super + r` etc. to work on all platforms
