### ISSUE TITLE
Makefile error on Linux

### ISSUE THREAD

**Issue by piatra** [slate/slate#73]
The `run` rule doesn't work on Linux because there is no `open`
Something like `/usr/lib/node-webkit/nw ./slate.nw` works just fine.
Should there be a `if` clause ? I could make a pull req but not sure how to treat it.

**Comment by tbranyen** [comment]
A parallel to open is xdg-open.

**Comment by hhsnopek** [comment]
New error present when running `make`

```
rm: cannot remove ‘/tmp/slate.nw’: Operation not permitted
make: *** [run] Error 1
```

I'm able to run `make build with no errors, but cannot make.

**Comment by ghost** [comment]
@HHSnopek, try `sudo`.

**Comment by hhsnopek** [comment]
@kelonye I then receive this error with `sudo make`

```
sudo make
[sudo] password for henry: 
zip -rq /tmp/slate.nw *
`which nw` /tmp/slate.nw
/bin/sh: 1: /tmp/slate.nw: Permission denied
make: *** [run] Error 126
```

**Comment by ghost** [comment]
@HHSnopek oh meant update target to `sudo `which nw` $(APP)`

**Comment by ghost** [comment]
@HHSnopek or build locally `APP = slate.nw`

**Comment by hhsnopek** [comment]
@kelonye I've tried both and a combination of both, I still receive an error of:

```
zip -rq ./slate.nw *
`sudo which nw` ./slate.nw
/bin/sh: 1: ./slate.nw: Permission denied
make: *** [run] Error 126
```

contents of makefile:

```

C8 = ./node_modules/.bin/component
SRC = $(wildcard lib/*/*.js)
APP = ./slate.nw

run: build
    @rm -f $(APP)
    zip -rq $(APP) *
ifeq ($(shell uname), Linux)
    `sudo which nw` $(APP)
else
    open -n -a node-webkit $(APP)
endif

build: node_modules components $(SRC)
    @$(C8) build --standalone slate

components:
    @$(C8) install

node_modules: package.json
    @npm install

clean:
    rm -fr build

distclean: clean
    rm -fr components

.PHONY: clean distclean run

```

EDIT: I have used `APP = slate.nw` & `which nw`

**Comment by noahbuscher** [comment]
And fix? I'm still getting the same error as @HHSnopek. :frowning:

**Comment by hhsnopek** [comment]
@Codingbean The furthest I've gotten is manually building without make. But once I finished I couldn't find where slate was placed :O

**Comment by hhsnopek** [comment]
Actually building it manually, I receive this error: `error : failed to lookup "boot"'s dependency "component-dom"
`

**Comment by noahbuscher** [comment]
Darn. Okay. Thanks for the suggestion! :smile_cat:
