### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by mkody** [slate/slate#82]
Well, wanted to take a look at slate, added an IRC server and channel and this happened: 

```
Uncaught node.js Error 

Error: read ECONNRESET
    at exports._errnoException (util.js:677:11)
    at TCP.onread (net.js:530:26)
```

![capture decran 2014-03-27 a 17 18 43](https://cloud.githubusercontent.com/assets/843787/2539775/76f53e4e-b5cb-11e3-80cc-dac41a64e918.png)

**Comment by rnarian** [comment]
Did you try and hit the back button?

**Comment by mkody** [comment]
Yes, I get the channels showing with the loading circles. But nothing else more.

**Comment by frdmn** [comment]
@mkody the application is work in progress and there are no additional functionalities at the moment.

**Comment by tj** [comment]
hmm are you connecting to freenode? I haven't had issues. It's annoying that node-webkit obscures the errors though, there's an open issue about that

**Comment by mkody** [comment]
@frdmn Yes, but the app _crash_ directly after the launch, it's not _"normal"_

@visionmedia I've tried with canternet.org and when I've re-cloned the repo, it tried to connect to another channels in a default server, and crashed.

**Comment by enwin** [comment]
I used to have the same problem when using the port 6697 instead of 6667.

Maybe a wrong port?

**Comment by mkody** [comment]
Using the default one, which is working on canternet.
